name: project_management_frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flame_splash_screen: ^0.1.0
  get_cli: ^1.8.1
  uni_links: ^0.5.1
  intl: ^0.17.0
  localstorage: ^4.0.0+1
  flutter_easyloading: ^3.0.5
  get: 4.6.5
  flutter_svg: ^1.0.0
  flutter_stripe: ^4.0.0
  url_launcher: ^6.1.5
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  multiselect: ^0.0.7
  html_editor_enhanced: ^2.5.0
  file_picker: ^4.6.1
  open_file: ^3.2.1
  simple_html_css: ^3.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/lang/
    - assets/icons/
    - assets/icons/menu_icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
    - family: DigitalNumbers
      fonts:
        - asset: assets/fonts/digital_numbers/DigitalNumbersr.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/bebas_neue/BebasNeue-Regular.ttf


